// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package main

import (
	"context"
)

const countBackgroundInbox = `-- name: CountBackgroundInbox :one
SELECT count(*) FROM inbox WHERE source = 'trigger'
`

func (q *Queries) CountBackgroundInbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBackgroundInbox)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInbox = `-- name: CountInbox :one
SELECT count(*) FROM inbox
`

func (q *Queries) CountInbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInbox)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutbox = `-- name: CountOutbox :one
SELECT count(*) FROM sent_messages WHERE conversation_id = ?
`

func (q *Queries) CountOutbox(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOutbox, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldestOutbox = `-- name: DeleteOldestOutbox :exec
DELETE FROM sent_messages
WHERE rowid IN (
    SELECT sm.rowid FROM sent_messages sm
    WHERE sm.conversation_id = ?
    ORDER BY sm.rowid ASC
    LIMIT ?
)
`

type DeleteOldestOutboxParams struct {
	ConversationID string
	Limit          int64
}

func (q *Queries) DeleteOldestOutbox(ctx context.Context, arg DeleteOldestOutboxParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldestOutbox, arg.ConversationID, arg.Limit)
	return err
}

const deleteRecurringReminder = `-- name: DeleteRecurringReminder :exec
DELETE FROM recurring_reminders WHERE id = ?
`

func (q *Queries) DeleteRecurringReminder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecurringReminder, id)
	return err
}

const deleteStaleItems = `-- name: DeleteStaleItems :exec
DELETE FROM inbox WHERE source IN ('heartbeat', 'compact')
`

func (q *Queries) DeleteStaleItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStaleItems)
	return err
}

const dequeueBackgroundInbox = `-- name: DequeueBackgroundInbox :one
DELETE FROM inbox
WHERE id = (
    SELECT id FROM inbox
    WHERE source = 'trigger'
    ORDER BY priority ASC, id ASC
    LIMIT 1
)
RETURNING id, priority, source, content, reply_to, conversation_id,
          message_id, is_group, created_at
`

func (q *Queries) DequeueBackgroundInbox(ctx context.Context) (Inbox, error) {
	row := q.db.QueryRowContext(ctx, dequeueBackgroundInbox)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Source,
		&i.Content,
		&i.ReplyTo,
		&i.ConversationID,
		&i.MessageID,
		&i.IsGroup,
		&i.CreatedAt,
	)
	return i, err
}

const dequeueChatInbox = `-- name: DequeueChatInbox :one
DELETE FROM inbox
WHERE id = (
    SELECT id FROM inbox
    WHERE source IN ('user', 'compact')
    ORDER BY priority ASC, id ASC
    LIMIT 1
)
RETURNING id, priority, source, content, reply_to, conversation_id,
          message_id, is_group, created_at
`

func (q *Queries) DequeueChatInbox(ctx context.Context) (Inbox, error) {
	row := q.db.QueryRowContext(ctx, dequeueChatInbox)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Source,
		&i.Content,
		&i.ReplyTo,
		&i.ConversationID,
		&i.MessageID,
		&i.IsGroup,
		&i.CreatedAt,
	)
	return i, err
}

const dueReminders = `-- name: DueReminders :many
DELETE FROM reminders
WHERE datetime(fire_at) <= datetime(?)
RETURNING id, fire_at, prompt
`

// datetime() normalizes ISO 8601 variants (Z vs +00:00, T vs space) so
// lexicographic comparison doesn't break on agent-formatted timestamps.
func (q *Queries) DueReminders(ctx context.Context, datetime interface{}) ([]Reminders, error) {
	rows, err := q.db.QueryContext(ctx, dueReminders, datetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminders
	for rows.Next() {
		var i Reminders
		if err := rows.Scan(&i.ID, &i.FireAt, &i.Prompt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueInbox = `-- name: EnqueueInbox :exec
INSERT INTO inbox (
    priority, source, content, reply_to, conversation_id, message_id, is_group
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type EnqueueInboxParams struct {
	Priority       int64
	Source         string
	Content        string
	ReplyTo        string
	ConversationID string
	MessageID      string
	IsGroup        bool
}

func (q *Queries) EnqueueInbox(ctx context.Context, arg EnqueueInboxParams) error {
	_, err := q.db.ExecContext(ctx, enqueueInbox,
		arg.Priority,
		arg.Source,
		arg.Content,
		arg.ReplyTo,
		arg.ConversationID,
		arg.MessageID,
		arg.IsGroup,
	)
	return err
}

const getOutbox = `-- name: GetOutbox :one
SELECT text FROM sent_messages
WHERE conversation_id = ? AND message_id = ?
`

type GetOutboxParams struct {
	ConversationID string
	MessageID      string
}

func (q *Queries) GetOutbox(ctx context.Context, arg GetOutboxParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getOutbox, arg.ConversationID, arg.MessageID)
	var text string
	err := row.Scan(&text)
	return text, err
}

const insertReminder = `-- name: InsertReminder :exec
INSERT INTO reminders (fire_at, prompt) VALUES (?, ?)
`

type InsertReminderParams struct {
	FireAt string
	Prompt string
}

func (q *Queries) InsertReminder(ctx context.Context, arg InsertReminderParams) error {
	_, err := q.db.ExecContext(ctx, insertReminder, arg.FireAt, arg.Prompt)
	return err
}

const listRecurringReminders = `-- name: ListRecurringReminders :many
SELECT id, cron, timezone, end_at, prompt
FROM recurring_reminders
ORDER BY id
`

func (q *Queries) ListRecurringReminders(ctx context.Context) ([]RecurringReminders, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringReminders
	for rows.Next() {
		var i RecurringReminders
		if err := rows.Scan(
			&i.ID,
			&i.Cron,
			&i.Timezone,
			&i.EndAt,
			&i.Prompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOutbox = `-- name: UpsertOutbox :exec
INSERT INTO sent_messages (conversation_id, message_id, text)
VALUES (?, ?, ?)
ON CONFLICT(conversation_id, message_id) DO UPDATE SET text = excluded.text
`

type UpsertOutboxParams struct {
	ConversationID string
	MessageID      string
	Text           string
}

func (q *Queries) UpsertOutbox(ctx context.Context, arg UpsertOutboxParams) error {
	_, err := q.db.ExecContext(ctx, upsertOutbox, arg.ConversationID, arg.MessageID, arg.Text)
	return err
}
