// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package main

import (
	"database/sql"
)

type Inbox struct {
	ID             int64
	Priority       int64
	Source         string
	Content        string
	ReplyTo        string
	ConversationID string
	MessageID      string
	IsGroup        bool
	ClaimedAt      string
	CreatedAt      string
}

type RecurringReminders struct {
	ID       int64
	Cron     string
	Timezone string
	EndAt    sql.NullString
	Prompt   string
}

type Reminders struct {
	ID     int64
	FireAt string
	Prompt string
}

type RoomContext struct {
	ID             int64
	ConversationID string
	MessageID      string
	Speaker        string
	Worker         string
	SenderName     string
	SenderID       string
	Text           string
	CreatedAt      string
}

type RoomContextOmissions struct {
	ConversationID string
	DroppedCount   int64
}

type SentMessages struct {
	ConversationID string
	MessageID      string
	Text           string
}
