// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package main

type Inbox struct {
	ID        int64
	Priority  int64
	Source    string
	Content   string
	ReplyTo   string
	CreatedAt string
}

type Reminders struct {
	ID     int64
	FireAt string
	Prompt string
}

type SentMessages struct {
	ConversationID string
	MessageID      string
	Text           string
}
