// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package nostr

import (
	"context"
)

const countSeenRumors = `-- name: CountSeenRumors :one
SELECT count(*) FROM seen_rumors
`

func (q *Queries) CountSeenRumors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSeenRumors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePublishItem = `-- name: DeletePublishItem :exec
DELETE FROM publish_queue WHERE id = ?
`

func (q *Queries) DeletePublishItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePublishItem, id)
	return err
}

const insertPublishItem = `-- name: InsertPublishItem :execlastid
INSERT INTO publish_queue (event_json, relays, created_at) VALUES (?, ?, ?)
`

type InsertPublishItemParams struct {
	EventJson string
	Relays    string
	CreatedAt int64
}

func (q *Queries) InsertPublishItem(ctx context.Context, arg InsertPublishItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertPublishItem, arg.EventJson, arg.Relays, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertSeenRumorIfNew = `-- name: InsertSeenRumorIfNew :execrows
INSERT OR IGNORE INTO seen_rumors (id, seen) VALUES (?, ?)
`

type InsertSeenRumorIfNewParams struct {
	ID   string
	Seen int64
}

func (q *Queries) InsertSeenRumorIfNew(ctx context.Context, arg InsertSeenRumorIfNewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSeenRumorIfNew, arg.ID, arg.Seen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPublishQueue = `-- name: ListPublishQueue :many
SELECT id, event_json, relays, created_at FROM publish_queue ORDER BY created_at, id
`

func (q *Queries) ListPublishQueue(ctx context.Context) ([]PublishQueue, error) {
	rows, err := q.db.QueryContext(ctx, listPublishQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishQueue
	for rows.Next() {
		var i PublishQueue
		if err := rows.Scan(
			&i.ID,
			&i.EventJson,
			&i.Relays,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newestSeenRumor = `-- name: NewestSeenRumor :one
SELECT CAST(COALESCE(max(seen), 0) AS INTEGER) FROM seen_rumors
`

func (q *Queries) NewestSeenRumor(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, newestSeenRumor)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneSeenRumors = `-- name: PruneSeenRumors :exec
DELETE FROM seen_rumors WHERE seen < ?
`

func (q *Queries) PruneSeenRumors(ctx context.Context, seen int64) error {
	_, err := q.db.ExecContext(ctx, pruneSeenRumors, seen)
	return err
}

const upsertSeenRumor = `-- name: UpsertSeenRumor :exec
INSERT INTO seen_rumors (id, seen) VALUES (?, ?)
ON CONFLICT(id) DO UPDATE SET seen = excluded.seen
`

type UpsertSeenRumorParams struct {
	ID   string
	Seen int64
}

func (q *Queries) UpsertSeenRumor(ctx context.Context, arg UpsertSeenRumorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSeenRumor, arg.ID, arg.Seen)
	return err
}
