// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package nostr

type PublishQueue struct {
	ID        int64
	EventJson string
	Relays    string
	CreatedAt int64
}

type SeenRumors struct {
	ID   string
	Seen int64
}
